// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE

import * as React from "react";
import * as React$1 from "@storybook/react";

var _module = (module);

React$1.storiesOf("My First Reason Story", _module).add("first chapter", (function () {
        return React.createElement("span", undefined, "Hello bs-storybook!");
      }));

export {
  _module ,
  
}
/* _module Not a pure module */
