// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "../../../node_modules/reason-react/lib/es6_global/src/ReasonReact.js";
import * as Js_primitive from "../../../node_modules/bs-platform/lib/es6/js_primitive.js";
import * as React$1 from "@storybook/react";
import * as Button$ReactTemplate from "./Button.js";

var _module = (module);

var baseColor = {
  r: 255,
  g: 99,
  b: 71,
  a: 1.0
};

var hoverBaseColor = {
  r: 255,
  g: 84,
  b: 166,
  a: 1.0
};

var textColor = {
  r: 235,
  g: 235,
  b: 235,
  a: 1.0
};

React$1.storiesOf("Button", _module).add("Standard button", (function () {
                return ReasonReact.element(undefined, undefined, Button$ReactTemplate.make(baseColor, textColor, undefined, undefined, undefined, Js_primitive.some(hoverBaseColor), undefined, {
                                fontSize: "22px",
                                padding: "10px 45px"
                              }, /* array */["Grab some water"]));
              })).add("Inverse", (function () {
              return ReasonReact.element(undefined, undefined, Button$ReactTemplate.make(baseColor, textColor, true, undefined, undefined, Js_primitive.some(hoverBaseColor), undefined, {
                              fontSize: "22px",
                              padding: "10px 45px"
                            }, /* array */["Grab some water"]));
            })).add("Inverse/transparent", (function () {
            return ReasonReact.element(undefined, undefined, Button$ReactTemplate.make(baseColor, textColor, true, "transparent", undefined, Js_primitive.some(hoverBaseColor), undefined, {
                            fontSize: "22px",
                            padding: "10px 45px"
                          }, /* array */["Grab some water"]));
          })).add("Ripple hover style", (function () {
          return ReasonReact.element(undefined, undefined, Button$ReactTemplate.make(baseColor, textColor, undefined, undefined, "ripple", Js_primitive.some(baseColor), undefined, {
                          fontSize: "22px",
                          padding: "10px 45px"
                        }, /* array */["Grab some water"]));
        })).add("Button with an anchor tag", (function () {
        return ReasonReact.element(undefined, undefined, Button$ReactTemplate.make(baseColor, textColor, undefined, undefined, undefined, Js_primitive.some(hoverBaseColor), undefined, {
                        fontSize: "22px",
                        padding: "10px 45px"
                      }, /* array */[React.createElement("a", {
                              href: "https://www.google.com/search?source=hp&ei=JRZpW4W9L-Td0gLe3rTACQ&q=Learn+about+reasonml&oq=Learn+about+reasonml&gs_l=psy-ab.3..0i22i30k1.869.3209.0.3434.21.14.0.0.0.0.200.1738.0j10j1.11.0....0...1.1.64.psy-ab..10.11.1737.0..0j35i39k1j0i131k1j0i13i30k1.0.RzvBa0sIOSw",
                              target: "_blank"
                            }, "Learn about ReasonML")]));
      }));

export {
  _module ,
  baseColor ,
  hoverBaseColor ,
  textColor ,
  
}
/* _module Not a pure module */
