// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "../../../node_modules/reason-react/lib/es6_global/src/ReasonReact.js";
import * as Caml_oo_curry from "../../../node_modules/bs-platform/lib/es6/caml_oo_curry.js";

var component = ReasonReact.statelessComponent("ContentMarquee");

function str(prim) {
  return prim;
}

function make(gradient, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, React.createElement("h2", undefined, "Some Title"), ReasonReact.createDomElement("div", {
                              gradient: gradient
                            }, children));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(Caml_oo_curry.js1(708786672, 2, jsProps), Caml_oo_curry.js1(-261482177, 1, jsProps));
      }));

export {
  component ,
  str ,
  make ,
  $$default ,
  $$default as default,
  
}
/* component Not a pure module */
