// Generated by BUCKLESCRIPT VERSION 4.0.2, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "../../../node_modules/reason-react/lib/es6_global/src/ReasonReact.js";
import * as React$1 from "@storybook/react";
import * as ContentMarquee$ReactTemplate from "./ContentMarquee.js";

var _module = (module);

React$1.storiesOf("ContentMarquee", _module).add("Without gradient", (function () {
          return ReasonReact.element(undefined, undefined, ContentMarquee$ReactTemplate.make("https://loremflickr.com/1400/400", undefined, {
                          color: "white",
                          fontSize: "45px",
                          padding: "80px"
                        }, /* array */[
                          React.createElement("h2", undefined, "Try our newest flavor!", React.createElement("br", undefined), React.createElement("em", {
                                    style: {
                                      color: "yellow"
                                    }
                                  }, "banana by bananarama")),
                          React.createElement("button", undefined, "Get some")
                        ]));
        })).add("With gradient", (function () {
        return ReasonReact.element(undefined, undefined, ContentMarquee$ReactTemplate.make("https://loremflickr.com/1400/400", "linear-gradient(to right, rgb(74, 194, 154), rgba(189, 255, 243, 0.5))", {
                        color: "white",
                        fontSize: "45px",
                        padding: "80px"
                      }, /* array */[
                        React.createElement("h2", undefined, "Try our newest flavor!", React.createElement("br", undefined), React.createElement("em", {
                                  style: {
                                    color: "yellow"
                                  }
                                }, "banana by bananarama")),
                        React.createElement("button", undefined, "Get some")
                      ]));
      }));

export {
  _module ,
  
}
/* _module Not a pure module */
