// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "../../../node_modules/reason-react/lib/es6_global/src/ReasonReact.js";
import * as React$1 from "@storybook/react";
import * as ContentMarquee$ReactTemplate from "./ContentMarquee.js";

var _module = (module);

React$1.storiesOf("ContentMarquee", _module).add("first chapter", (function () {
        return ReasonReact.element(undefined, undefined, ContentMarquee$ReactTemplate.make("https://loremflickr.com/1400/400", "linear-gradient(to right, rgb(74, 194, 154), rgba(189, 255, 243, 0.5))", {
                        padding: "80px"
                      }, /* array */[React.createElement("span", undefined, "this is some children stuff")]));
      }));

export {
  _module ,
  
}
/* _module Not a pure module */
