// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE

import * as ReasonReact from "../../../node_modules/reason-react/lib/es6_global/src/ReasonReact.js";
import * as React from "@storybook/react";
import * as HelloWorld$ReactTemplate from "./HelloWorld.js";

var _module = (module);

React.storiesOf("HelloWorld", _module).add("first chapter", (function () {
        return ReasonReact.element(undefined, undefined, HelloWorld$ReactTemplate.make("Logan", /* array */[]));
      }));

export {
  _module ,
  
}
/* _module Not a pure module */
