// Generated by BUCKLESCRIPT VERSION 4.0.2, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "../../../node_modules/reason-react/lib/es6_global/src/ReactDOMRe.js";
import * as Js_primitive from "../../../node_modules/bs-platform/lib/es6/js_primitive.js";

function combineWithOptionalStyles(styles, styles2) {
  if (styles2 !== undefined) {
    return ReactDOMRe.Style[/* combine */0](styles, Js_primitive.valFromOption(styles2));
  } else {
    return styles;
  }
}

export {
  combineWithOptionalStyles ,
  
}
/* ReactDOMRe Not a pure module */
