// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/lib/es6/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as Js_primitive from "bs-platform/lib/es6/js_primitive.js";
import * as StyleUtils$SeamonsterStudiosReactComponents from "./StyleUtils.bs.js";

var component = ReasonReact.statelessComponent("ContentMarquee");

function make(image, gradient, style, className, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReactDOMRe.createElementVariadic("div", {
                          className: "component-content-marquee " + (
                            className !== undefined ? className : ""
                          ),
                          style: StyleUtils$SeamonsterStudiosReactComponents.combineWithOptionalStyles({
                                background: (
                                  gradient !== undefined ? gradient : "linear-gradient(rgba(255, 255, 255, 0),rgba(255, 255, 255, 0))"
                                ) + (", url(" + (image + ")")),
                                backgroundPosition: "center center",
                                backgroundSize: "cover"
                              }, style)
                        }, children);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.image, Js_primitive.nullable_to_opt(jsProps.gradient), Js_primitive.nullable_to_opt(jsProps.style), Js_primitive.nullable_to_opt(jsProps.className), jsProps.children);
      }));

export {
  component ,
  make ,
  $$default ,
  $$default as default,
  
}
/* component Not a pure module */
