// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE

import * as Css from "bs-css/lib/es6/src/Css.js";
import * as ReactDOMRe from "reason-react/lib/es6/src/ReactDOMRe.js";
import * as Js_primitive from "bs-platform/lib/es6/js_primitive.js";

function combineWithOptionalStyles(styles, styles2) {
  if (styles2 !== undefined) {
    return ReactDOMRe.Style[/* combine */0](styles, Js_primitive.valFromOption(styles2));
  } else {
    return styles;
  }
}

function color_of_rgba(color) {
  return Css.rgba(color.r, color.g, color.b, color.a);
}

function cssInherit(x) {
  return Css.unsafe(x, "inherit");
}

function pseudoContent(x) {
  return Css.unsafe("content", x);
}

export {
  combineWithOptionalStyles ,
  color_of_rgba ,
  cssInherit ,
  pseudoContent ,
  
}
/* Css Not a pure module */
