// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var StyleUtils = require("./StyleUtils.bs.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

var component = ReasonReact.statelessComponent("ContentMarquee");

function make(image, gradient, style, className, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReactDOMRe.createElementVariadic("div", {
                          className: "component-content-marquee " + (
                            className !== undefined ? className : ""
                          ),
                          style: StyleUtils.combineWithOptionalStyles({
                                background: (
                                  gradient !== undefined ? gradient : "linear-gradient(rgba(255, 255, 255, 0),rgba(255, 255, 255, 0))"
                                ) + (", url(" + (image + ")")),
                                backgroundPosition: "center center",
                                backgroundSize: "cover"
                              }, style)
                        }, children);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.image, Js_primitive.nullable_to_opt(jsProps.gradient), Js_primitive.nullable_to_opt(jsProps.style), Js_primitive.nullable_to_opt(jsProps.className), jsProps.children);
      }));

exports.component = component;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
